/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediadorActasRouteImport } from './routes/mediador.actas'
import { Route as MediadorCasoCaseIdRouteImport } from './routes/mediador.caso.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediadorActasRoute = MediadorActasRouteImport.update({
  id: '/mediador/actas',
  path: '/mediador/actas',
  getParentRoute: () => rootRouteImport,
} as any)
const MediadorCasoCaseIdRoute = MediadorCasoCaseIdRouteImport.update({
  id: '/mediador/caso/$caseId',
  path: '/mediador/caso/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mediador/actas': typeof MediadorActasRoute
  '/mediador/caso/$caseId': typeof MediadorCasoCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mediador/actas': typeof MediadorActasRoute
  '/mediador/caso/$caseId': typeof MediadorCasoCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mediador/actas': typeof MediadorActasRoute
  '/mediador/caso/$caseId': typeof MediadorCasoCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mediador/actas' | '/mediador/caso/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mediador/actas' | '/mediador/caso/$caseId'
  id: '__root__' | '/' | '/mediador/actas' | '/mediador/caso/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediadorActasRoute: typeof MediadorActasRoute
  MediadorCasoCaseIdRoute: typeof MediadorCasoCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediador/actas': {
      id: '/mediador/actas'
      path: '/mediador/actas'
      fullPath: '/mediador/actas'
      preLoaderRoute: typeof MediadorActasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediador/caso/$caseId': {
      id: '/mediador/caso/$caseId'
      path: '/mediador/caso/$caseId'
      fullPath: '/mediador/caso/$caseId'
      preLoaderRoute: typeof MediadorCasoCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediadorActasRoute: MediadorActasRoute,
  MediadorCasoCaseIdRoute: MediadorCasoCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
